apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apache-superset
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    # Nguồn 1: Helm Chart gốc từ Apache
    - repoURL: 'https://apache.github.io/superset'
      chart: superset
      targetRevision: 0.22.4
      helm:
        valueFiles:
          # Vì file nằm ở gốc Repo nên chỉ cần $my-git-repo/values-superset.yaml
          - $my-git-repo/values-superset.yaml

    # Nguồn 2: URL Git thực tế trên GitHub của bạn
    - repoURL: 'https://github.com/minhkhacode/superset-gitops.git'
      targetRevision: main # Nhánh thực tế trong hình của bạn là main
      ref: my-git-repo

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: superset

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true